---
- name: Update apt packages
  become: true
  apt:
    update_cache: yes
- name: Upgrade apt packages
  become: true
  apt:
    upgrade: yes
- name: Remove unneeded dependencies
  become: true
  apt:
    autoremove: yes
- name: Install dependencies
  become: true
  apt:
    name: [nodejs, npm]
    state: present
    update_cache: yes
- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# VS Code Extension Version: 1.4.0