---
- name: Extract archive files
  become: true
  unarchive:
    src: ./artifact.tar.gz
    dest: .

- name: Stop and start app
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start

# VS Code Extension Version: 1.5.0